services:
  msrabbitmq:
    image: rabbitmq:3.10.5-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=tugsef
      - RABBITMQ_DEFAULT_PASS=tugsef